
export const data=[
  {
    "tabName": "Tabs",
    "displayName": "Tabs",
    "displayType": 1,
    "webPage": "/Tabs",
    "parentId": "356155b70778431dbfacf5ac98649a5e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddTab",
    "isMenu": false,
    "iconName": "",
    "displayOrder": 1,
    "encryptedTabId": "adb399ae69ad081848002bd9b928e4ad"
  },
  {
    "tabName": "CMS",
    "displayName": "CMS",
    "displayType": 1,
    "webPage": null,
    "parentId": "0",
    "isActive": true,
    "isAdd": null,
    "isEdit": null,
    "isDelete": null,
    "isView": true,
    "addWebpage": null,
    "isMenu": null,
    "iconName": null,
    "displayOrder": 2,
    "encryptedTabId": "356155b70778431dbfacf5ac98649a5e"
  },
  {
    "tabName": "Roles",
    "displayName": "Roles",
    "displayType": 1,
    "webPage": "/Roles",
    "parentId": "356155b70778431dbfacf5ac98649a5e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddRoles",
    "isMenu": true,
    "iconName": "",
    "displayOrder": 2,
    "encryptedTabId": "eba826a352f83c1b3d7c3c8d30f91b2d"
  },
  {
    "tabName": "Users",
    "displayName": "Users",
    "displayType": 1,
    "webPage": "/Users",
    "parentId": "356155b70778431dbfacf5ac98649a5e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddUsers",
    "isMenu": null,
    "iconName": null,
    "displayOrder": 3,
    "encryptedTabId": "81ea451e6c0d6a2f9ecf8ca66bd7c1fe"
  },
  {
    "tabName": "Master",
    "displayName": "Master",
    "displayType": 1,
    "webPage": null,
    "parentId": "0",
    "isActive": true,
    "isAdd": null,
    "isEdit": null,
    "isDelete": null,
    "isView": true,
    "addWebpage": null,
    "isMenu": null,
    "iconName": null,
    "displayOrder": 1,
    "encryptedTabId": "ee41f219296d0c07db6d0d18d4c46e0e"
  },
  {
    "tabName": "Event Types",
    "displayName": "Event Types",
    "displayType": 1,
    "webPage": "/EventType",
    "parentId": "ee41f219296d0c07db6d0d18d4c46e0e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddEventsType",
    "isMenu": null,
    "iconName": null,
    "displayOrder": 1,
    "encryptedTabId": "d69645e91835dc17fa172e44499ee2b1"
  },
  {
    "tabName": "Players",
    "displayName": "Players",
    "displayType": 1,
    "webPage": "/Players",
    "parentId": "ee41f219296d0c07db6d0d18d4c46e0e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddPlayers",
    "isMenu": null,
    "iconName": null,
    "displayOrder": 2,
    "encryptedTabId": "c6dce067c2653c9dbbc627bc2f1949bb"
  },
  {
    "tabName": "Teams",
    "displayName": "Teams",
    "displayType": 1,
    "webPage": "/Teams",
    "parentId": "ee41f219296d0c07db6d0d18d4c46e0e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddTeams",
    "isMenu": null,
    "iconName": null,
    "displayOrder": 3,
    "encryptedTabId": "2a3c8d373661e4a8dccb7904a2947bbc"
  },
  {
    "tabName": "Match Types",
    "displayName": "Match Types",
    "displayType": 1,
    "webPage": "/MatchType",
    "parentId": "ee41f219296d0c07db6d0d18d4c46e0e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddMatchType",
    "isMenu": null,
    "iconName": null,
    "displayOrder": 4,
    "encryptedTabId": "3f238258e9d16e432c1ca7067e0b73b2"
  },
  {
    "tabName": "Panelty Runs",
    "displayName": "Panelty Runs",
    "displayType": 1,
    "webPage": "/Penalty",
    "parentId": "ee41f219296d0c07db6d0d18d4c46e0e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddPenalty",
    "isMenu": null,
    "iconName": null,
    "displayOrder": 5,
    "encryptedTabId": "27016e93f28ee644ab8771727910d0a3"
  },
  {
    "tabName": "Competition",
    "displayName": "Competition",
    "displayType": 1,
    "webPage": "/Competition",
    "parentId": "ee41f219296d0c07db6d0d18d4c46e0e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddCompetition",
    "isMenu": null,
    "iconName": null,
    "displayOrder": 6,
    "encryptedTabId": "4c43155fcfe2e3b85ee9ebec31e28807"
  },
  {
    "tabName": "Events",
    "displayName": "Events",
    "displayType": 1,
    "webPage": "/Events",
    "parentId": "ee41f219296d0c07db6d0d18d4c46e0e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddEvents",
    "isMenu": null,
    "iconName": null,
    "displayOrder": 7,
    "encryptedTabId": "a194a6cc9fc8d82f4cfe33d3722633bc"
  },
  {
    "tabName": "Commentary",
    "displayName": "Commentary",
    "displayType": 1,
    "webPage": "/Commentary",
    "parentId": "ee41f219296d0c07db6d0d18d4c46e0e",
    "isActive": true,
    "isAdd": true,
    "isEdit": true,
    "isDelete": true,
    "isView": true,
    "addWebpage": "/AddCommentary",
    "isMenu": true,
    "iconName": null,
    "displayOrder": 8,
    "encryptedTabId": "7dbcb2df3599f6813bf8971a94235237"
  }
]